spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://postgres:5432/fitlocity_gym
    username: ajaydangoriyatharu
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 4001

jwt:
  secret: supersecretkey
  expiry: 3600000