server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/fitlocity_gym
    username: ajaydangoriyatharu
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false

jwt:
  secret: ${JWT_SECRET:12345678901234567890123456789012}
  expiration: 86400000